name: my_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  common_models: ^0.0.1
  # common_models: ^0.0.1
  #   path: ../../packages/common_models
  dart_frog: ^0.3.0
  isar: 3.0.6-dev.0
  



dev_dependencies:
  build_runner: any
  isar_generator: 3.0.6-dev.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  


